import"./assets/styles-JE8YjOlG.js";import{a as r}from"./assets/vendor-2s9xPmg-.js";const P="https://dummyjson.com",l={PRODUCTS:"/products",PRODUCTS_BY_ID:"/products/",CATEGORIES:"/products/category-list",CATEGORY:"products/category/",SEARCH:"/products/search"},d=12,s={QUERY:"",PAGE:1},c={closeModalBtn:document.querySelector(".modal__close-btn"),modal:document.querySelector(".modal"),body:document.querySelector("body"),themeToggleBtn:document.querySelector(".theme-toggle-btn"),categoriesList:document.querySelector(".categories"),productsList:document.querySelector(".products"),notFoundBlock:document.querySelector("div.not-found"),modalContainer:document.querySelector(".modal-product")};function v(){c.productsList.innerHTML=""}function k(t){const o=document.querySelector(".categories__btn--active");o&&o.classList.remove("categories__btn--active"),t.classList.add("categories__btn--active")}function C(){c.notFoundBlock.classList.add("not-found--visible")}function S(){c.notFoundBlock.classList.remove("not-found--visible")}r.defaults.baseURL=P;async function y(t){const o=(t-1)*d,{data:n}=await r.get(`${l.PRODUCTS}?limit=${d}&skip=${o}`);return n}async function A(){const{data:t}=await r.get(l.CATEGORIES);return t}async function T(t,o){const n=(o-1)*d,{data:e}=await r.get(`${l.CATEGORY}${t}?limit=${d}&skip=${n}`);return e}async function w(t){const{data:o}=await r.get(`${l.PRODUCTS_BY_ID}${t}`);return o}async function _(t){const o=t.map(({thumbnail:n,id:e,description:u,title:a,price:p,category:m,brand:i})=>`<li class="products__item" data-id="${e}">
    <img class="products__image" src="${n}" alt="${u}"/>
    <p class="products__title">${a}</p>
    <p class="products__brand"><span class="products__brand--bold">Brand:${i||"no brand"}</span></p>
    <p class="products__category">Category: ${m}</p>
    <p class="products__price">Price: ${p}$</p>
 </li>`).join("");c.productsList.insertAdjacentHTML("beforeEnd",o)}function B(t){const n=["All",...t].map(e=>`<li class="categories__item">
    <button class="categories__btn" type="button">${e}</button>
    </li>`).join("");c.categoriesList.innerHTML=n}function h(t){if(!c.modalContainer)return;const{images:o=[],thumbnail:n="",title:e="Unnamed product",description:u="—",price:a=null,brand:p="",category:m="",tags:i}=t||{},L=o[0]||n||"",b=(Array.isArray(i)?i:[p,m].filter(Boolean)).map($=>`<li>${String($)}</li>`).join("");c.modalContainer.innerHTML=`
    <img class="modal-product__img" src="${L}" alt="${e}" />
    <div class="modal-product__content">
      <p class="modal-product__title">${e}</p>
      <ul class="modal-product__tags">${b}</ul>
      <p class="modal-product__description">${u}</p>
      <p class="modal-product__shipping-information">Shipping: —</p>
      <p class="modal-product__return-policy">Return Policy: —</p>
      <p class="modal-product__price">Price: $${a!=null?Number(a).toFixed(2):"—"}</p>
      <button class="modal-product__buy-btn" type="button">Buy</button>
    </div>
  `}function R(){c.modal.classList.add("modal--is-open"),c.body.style.overflow="hidden",window.addEventListener("keydown",f),c.modal.addEventListener("click",E)}function g(){c.modal.classList.remove("modal--is-open"),c.body.style.overflow="",window.removeEventListener("keydown",f),c.modal.removeEventListener("click",E)}function f(t){t.code==="Escape"&&g()}function E(t){t.currentTarget===t.target&&g()}async function G(){try{const t=await A();B(t);const{products:o}=await y(s.PAGE);_(o)}catch{}}async function M(t){const o=t.target.closest(".categories__btn");if(!o)return;v(),k(o),S(),s.PAGE=1;const n=o.textContent;if(n==="All")try{const{products:e}=await y(s.PAGE);_(e)}catch(e){console.error(`Get products error: ${e}`)}else{s.QUERY=n;try{const{products:e}=await T(s.QUERY,s.PAGE);e.length===0?C():_(e)}catch(e){console.error(`Get products error: ${e}`)}}}async function q(t){const o=t.target.closest(".products__item");if(!o||!c.productsList.contains(o))return;const n=o.dataset.id;if(n)try{const e=await w(n);h(e),R()}catch(e){console.error("Не вдалося завантажити продукт:",e)}}document.addEventListener("DOMContentLoaded",G);c.closeModalBtn.addEventListener("click",g);c.categoriesList.addEventListener("click",M);c.productsList.addEventListener("click",q);
//# sourceMappingURL=index.js.map
